### PR TITLE
C++11

### PR DESCRIPTION
**Pull request by stribor14**
- Use of stl::move when applicable
- Replaced QTL foreach with STL range-for; since Qt's foreach macro will be removed in future updates (5.7 onward), it is advised to use c++11 range-for loop. Also, foreach makes copy of data while range-for can work with reference on data.
- Replaced comparison functions for sort algorithms with lambda expressions
- Added macros to use as dynamic & static cast for most common casted types (and to improve readabilty of code)

### CODE REVIEW

**Comment by stribor14** [comment]
note for shared_ptr :  although useful in future c++ projects, it doesn't fit well with QTL functions and Qt object manager

**Comment by stribor14** [comment]
Last commit needs discussion before being pulled

**Comment by stribor14** [comment]
Pull request should wait till issue #71 is closed so code refactoring would be completely done.

**Comment by dmiklic** [comment]
I should wait with the merge until you push a fix for #71?

**Comment by stribor14** [comment]
Yes, it will be done soon

**Comment by stribor14** [comment]
C++11 refacturing is complete + deployment tab is done in Qt Designer (issue #53)
Pull request can wait until QDialogConnect and QDialogSettings are done in Qt Designer. (QDialogSetpoint will remain in code version because his form depends on setpoint actuator)

**Comment by dmiklic** [comment]
Is this ready to merge now?

**Comment by stribor14** [comment]
It is ready, all issues that could be clossed are clossed.

**Pull request merged**
